### ISSUE TITLE
Switch to using tarrell13/Egress-Assess/master branch

### ISSUE THREAD

**Issue by m1j09830** [cisagov/kali-packer#139]
# 💡 Summary #

Switch to using [`tarrell13/Egress-Assess/master`](https://github.com/tarrell13/Egress-Assess/tree/master) branch for the Egress-Assess tool.

## Motivation and context ##

We are currently using the `tarrell13/Egress-Assess/Forked` branch due to merge conflicts with `master` at the time of testing. When the `Forked` and `master` branches have been merged the [`archive_src`](https://github.com/cisagov/egress-assess-packer/blob/5217f6e26b6c0d46e766cb687ce04ac8890682a6/src/egress_assess.yml#L9-L10) will need to be updated to use `tarrell13/Egress-Assess/master`. 

## Implementation notes ##

None

## Acceptance criteria ##

- [ ] We are using master branch of `tarrell13/Egress-Assess`

**Comment by m1j09830** [comment]
@tarrell13 made a new repository with the name Auto-Egress-Assess. The new repository has been incorporated into the `assessor-tools.yml` file in https://github.com/cisagov/kali-packer/commit/e06b3432e21f269d380abf6225c3a30d645ca2d2. Therefore this issue is no longer needed.

**Comment by jsf9k** [comment]
This work wasn't completed, but instead was overtaken by events and is no longer being planned.
