### ISSUE TITLE
Remove Empire Tool

### ISSUE THREAD

**Issue by m1j09830** [cisagov/kali-packer#142]
# 💡 Summary #

We would like to remove the Empire tool as this is not actively being used on engagements.

## Motivation and context ##

Empire is preventing the build of the current Kali AMI because of changes that were made to the repository which affected the install process. This tool is not currently used on engagements in a meaningful way so there is no need to have it on the system. In the extreme off chance that operators need it in the future they can clone the repository and install ad hoc. 

## Implementation notes ##

Remove the Empire tool from the kali-packer repo 

## Acceptance criteria ##

How do we know when this work is done?

- [x] Empire is no longer installed in the `/tools/` directory
- [x] The Kali AMI is able to successfully build

**Comment by jsf9k** [comment]
Resolved in #141.
