### ISSUE TITLE
Revert to the default branch of gantsign/visual-studio-code

### ISSUE THREAD

**Issue by jsf9k** [cisagov/kali-packer#153]
# 💡 Summary #

Revert to the default branch of [gantsign/visual-studio-code](https://github.com/gantsign/visual-studio-code) once https://github.com/gantsign/ansible-role-visual-studio-code/pull/244 is approved and merged.

## Motivation and context ##

Using a non-default branch was a necessary measure, since the default branch attempts to install the `gconf2` package and this package does not exist on Kali Linux.

**Comment by dav3r** [comment]
Now that https://github.com/gantsign/ansible-role-visual-studio-code/pull/244 has been merged, we are clear to revert the changes in https://github.com/cisagov/kali-packer/pull/152/commits/ec7e028baacbf41807983dccf543874f863c7b5c.
